### PR TITLE
fix: Bug fixes and improvements for Dark Mode

### LINKED ISSUE #3066: Color tokens: Bug fixes and improvements for Dark Mode
## Bug description
There are a few inconsistencies color bugs related to the color palette scheme and the dark mode styles. See some examples below in screenshots.
Some colors can use a replacement in the dark mode scheme to reflect on the colors of the light mode, some are just not following the existing color palette.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Settings > Notifications and Settings > Modules to see alert banners;
 2. Go to Safe Apps, see the sliding component above;
 3. Go to any page, open the Safe Accounts sidebar;
 4. Open a Safe Accounts with pending notifications to trigger Info alert;
 5. Open the network switcher in the top navbar.

## Expected result 
The following color codes should be applied in the **dark mode**

- `success:background` is `#1f2920`
- `secondary:background` is `#1B2A22`
- Background of the info notification color should be: `#19252C`
- The selected network color in the network dropdown should be: `#303033`
- In the Safe accounts list the color of the addresses should be text:primary (currently it's green)
- In the Safe apps component` styles_content__TMlnS` needs to use `#12FF80` for the border and the arrow component (can we change the hex code for `secondary:main` in darkPalette.ts to `#12FF80`?)

## Screenshots
1-success-background
1-secondary-background
safe-acc
network_color
Screenshot 2024-01-04 at 17 09 32

### PR DESCRIPTION
**Pull request by manoranjith-shankar**
## What it solves

Resolves #3066 

## How this PR fixes it
This pull request addresses color inconsistencies related to the color palette scheme and dark mode styles. The following changes have been made:

* [x] secondary:background is `#1B2A22`. previously(`#303033`) - no effect on custom component styles.
* [x] The selected network color in the network dropdown is changed to `#303033`. previously(`#1B2A22`).
* [x] In the Safe apps component styles_content__TMlnS now uses `#12FF80` for the border and the arrow component
     - __can we change the hex code for secondary:main in darkPalette.ts to `#12FF80`?__ 
     if we change this colour definition, custom theme definitions could be overidded causing color inconsistencies for few custom component, to avoid this, explicit color definitions were directly added to this component's css (https://github.com/manoranjith-shankar/safe-wallet-web/commit/1756419ba7f6ac682646e3d2aa5022d7778f5927).

### changes made (https://github.com/safe-global/safe-wallet-web/pull/3102/commits/0babf13e3bda91f2f764e99445440cab0ec3b403)

* [x] success:background is set to `#1f2920` by fixing the typo for alerts in `safeTheme.ts`.
* [x] Background of the info notification color is now `#19252C` in dark mode.
* [x] In the Safe accounts list, the color of the addresses is set to be text:primary.

## How to test it

* Go to Safe Apps, see the sliding component above;
* Open the network switcher in the top navbar.
* Go to Settings > Notifications and Settings > Modules to see alert banners;
* Go to any page, open the Safe Accounts sidebar;
* Open a Safe Accounts with pending notifications to trigger Info alert;

## Screenshots
PR-2-1
PR-2-2
PR-2-3
PR-2-4
PR-2-5
PR-2-6

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've tested on light theme for any color inconsistencies
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
Thank you!

**Comment by usame-algan** [comment]
> success:background is #1f2920 - already set as same. reference: darkPalette.ts

I checked and the color is currently not applied to the Alert element inside `safeTheme.ts` because of a typo. It should say `'&.MuiPaper-root':` instead of `'& .MuiPaper-root':`. I think this also applies to all other `MuiAlert` overrides.

**Comment by usame-algan** [comment]
> Background of the info notification color: #19252C - already set as same. reference: darkPalette.ts

This is overwritten via css in `src/components/settings/PushNotifications/styles.module.css`

**Comment by usame-algan** [comment]
> In the Safe accounts list, the color of the addresses is already set to be text:primary - no changes made.

Its currently set to `primary` but should be `text.primary` inside the `SafeListItem` component

**Comment by manoranjith-shankar** [comment]
> > success:background is #1f2920 - already set as same. reference: darkPalette.ts
> 
> I checked and the color is currently not applied to the Alert element inside `safeTheme.ts` because of a typo. It should say `'&.MuiPaper-root':` instead of `'& .MuiPaper-root':`. I think this also applies to all other `MuiAlert` overrides.

@usame-algan, Thank you for the help. fixed the typo & other issues in this commit https://github.com/safe-global/safe-wallet-web/pull/3102/commits/0babf13e3bda91f2f764e99445440cab0ec3b403.

File: src/components/common/NetworkSelector/index.tsx [hunk 1]
```diff
@@ -112,6 +114,11 @@ const NetworkSelector = (props: { onChainSelect?: () => void }): ReactElement =>
           '& .MuiPaper-root': {
             overflow: 'auto',
           },
+          ...(theme.palette.mode == 'dark' && {
+            '& .Mui-selected': {
+              backgroundColor: '#303033 !important',
```
Comment (usame-algan) [inline src/components/common/NetworkSelector/index.tsx:119]:
```suggestion
            '& .Mui-selected, & .Mui-selected:hover': {
              backgroundColor: theme.palette.secondary.background,
```

File: src/components/common/NetworkSelector/index.tsx [hunk 2]
```diff
@@ -112,6 +114,11 @@ const NetworkSelector = (props: { onChainSelect?: () => void }): ReactElement =>
           '& .MuiPaper-root': {
             overflow: 'auto',
           },
+          ...(theme.palette.mode == 'dark' && {
```
Comment (usame-algan) [inline src/components/common/NetworkSelector/index.tsx:117]: We have a hook for this called `useDarkMode`. You can use it like this in the component: `const isDarkMode = useDarkMode()`

File: src/components/safe-apps/SafeAppsSDKLink/styles.module.css [hunk 3]
```diff
@@ -51,6 +51,11 @@
   left: 50%;
   bottom: -20px;
   margin-left: -25px;
+  background-color: #12ff80;
+}
+
+.openButton:hover {
+  background-color: #1ec46c;
```
Comment (usame-algan) [inline src/components/safe-apps/SafeAppsSDKLink/styles.module.css:58]:
```suggestion
  background-color: #0cb259;
```

File: src/components/settings/PushNotifications/styles.module.css [hunk 4]
```diff
@@ -27,3 +27,7 @@
   background-color: var(--color-secondary-background);
   padding: var(--space-2);
 }
+
+[data-theme='dark'] .globalInfo {
+  background-color: var(--color-info-background);
+}
```
Comment (usame-algan) [inline src/components/settings/PushNotifications/styles.module.css:33]: I think it would make more sense to use an `<Alert severity="info">` component otherwise we have a blueish background with a green border in dark mode which we don't have anywhere like this.

**Review by usame-algan — COMMENTED** [review]
Looking good! Just a few last suggestions.

File: src/components/settings/PushNotifications/styles.module.css (hunk 4 above)
Comment (manoranjith-shankar) [reply src/components/settings/PushNotifications/styles.module.css:33]: Actually, the background color change was mentioned to `#19252C` in the issue

Comment (katspaugh) [reply src/components/settings/PushNotifications/styles.module.css:33]: Let's keep it as per the issue then, we can later change it to `info` if needed.

**Comment by katspaugh** [comment]
Cheers @manoranjith-shankar!
