### PR TITLE
fix: close batch flow when removing last draft

### LINKED ISSUE #2428: [Batching] Remove tx while in the form
## Bug description

When confirming a tx batch, you can open the batch tx sidebar to reorder or delete tx. 
Is possible for the user to delete them all, end with a bogus tx that probably will fail if executed.

## Environment
 - Browser: Chrome
 - Wallet: any
 - Chain: any
 - Env: 1.17

## Steps to reproduce
 1. Go to a safe
 2. Add 2 tx to the batch
 3. Use the "Confirm transaction" button in the Batch tx sidebar so they are put in a single transaction
 4. While in the form, reopen the batch tx sidebar
 5. Remove the tx from the sidebar one by one

## Expected result

Tx shouldn't be executable after all transactions are gone

## Obtained result

A bogus tx remains, with a warning that the tx might fail.

## Screenshots
batch tx removal

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #2428

## How this PR fixes it

If the batch confirmation flow is open, it is now closed when the last draft is removed via the sidebar.

## How to test it

Batch transaction(s) and enter the confirmation flow. Whilst in the flow, remove the last draft from the sidebar and observe the confirmation flow close. It should _not_ close other flows that may be open under the sidebar.

## Screenshots

close-batch

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/batch/BatchSidebar/index.tsx [hunk 1]
```diff
@@ -27,6 +27,14 @@ const BatchSidebar = ({ isOpen, onToggle }: { isOpen: boolean; onToggle: (open:
     batchTxs.forEach((item) => deleteTx(item.id))
   }, [deleteTx, batchTxs])
 
+  // Close confirmation flow when batch is empty
+  const shouldExitFlow = !!txFlow && batchTxs.length === 0
+  useEffect(() => {
+    if (shouldExitFlow) {
+      setTxFlow(undefined)
```
Comment (usame-algan) [inline src/components/batch/BatchSidebar/index.tsx:34]: Can we somehow couple this to the user action i.e. add it to the `deleteTx` call instead of having it in a `useEffect`?

Comment (iamacook) [reply src/components/batch/BatchSidebar/index.tsx:34]: See https://github.com/safe-global/safe-wallet-web/pull/2453#discussion_r1307455063.

Comment (katspaugh) [reply src/components/batch/BatchSidebar/index.tsx:34]: Btw can there be a case when there’s some other tx flow open, not a batch modal?

File: src/components/batch/BatchSidebar/index.tsx [hunk 2]
```diff
@@ -35,6 +35,17 @@ const BatchSidebar = ({ isOpen, onToggle }: { isOpen: boolean; onToggle: (open:
...
 
+  const onDelete = useCallback(
+    (id: string) => {
+      const shouldCloseFlow = batchTxs.length === 1
+      deleteTx(id)
+      if (shouldCloseFlow) {
+        setTxFlow(undefined)
+      }
+    },
+    [deleteTx, batchTxs, setTxFlow],
```
[the remark this answers is not in the document]
Comment (usame-algan) [reply src/components/batch/BatchSidebar/index.tsx]: Is there a benefit of doing this in an effect over adding it to the onDelete handler?

File: src/components/batch/BatchSidebar/index.tsx (hunk 1 above)
Comment (iamacook) [reply src/components/batch/BatchSidebar/index.tsx:35]: > Btw can there be a case when there’s some other tx flow open, not a batch modal?

I've updated this accordingly.

File: src/components/batch/BatchSidebar/index.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (katspaugh) [reply src/components/batch/BatchSidebar/index.tsx]: On delete is probably more robust. But at the same time deleting a tx and closing a mods are two completely different actions. Closing the modal is a side effect of having nothing to display. A matter of taste in the end, imperative vs declarative.
