### PR TITLE
fix: close transaction flow if Safe changes

### LINKED ISSUE #2499: [Tx details] Tx details is not closed when another safe is selected
## Bug description
Tx details is not closed when another safe is selected

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli/any netwrok

## Steps to reproduce
 1. Start tx creation in the safe on Goerli
 2. don't submit tx
 3. switch safe ( choose the safe from another network)

## Expected result
Make sure that the user is asked if the tx details page should be closed before switching to another safe

## Video

https://github.com/safe-global/safe-wallet-web/assets/338622/9114d5c0-4582-41a2-b9ed-98765a285493

### LINKED ISSUE #2509: Filter by the token address doesn't work for the incoming filter
## Bug description
Filter by the token address doesn't work for the incoming filter
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: zkSync

## Steps to reproduce
 1. Go to https://app.safe.global/transactions/history?safe=arb1%3A0x861099a9FD94b03471a1002efCa662c3ECAdB10C&type=Incoming&token_address=0x82aF49447D8a07e3bd95BD0d56f35241523fBab1
 2.  the history is filtered by token address+incoming txs  ( 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1)

Request to the CGW - https://safe-client.safe.global/v1/chains/42161/safes/0x861099a9FD94b03471a1002efCa662c3ECAdB10C/incoming-transfers/?safe=arb1%3A0x861099a9FD94b03471a1002efCa662c3ECAdB10C&token_address=0x82aF49447D8a07e3bd95BD0d56f35241523fBab1

Current result: There are next issues:
1. outgoing and incoming txs are displayed ( because sender=receiver)
2. the same txs is displayed twice when the filter is used ( check tx hash). At the same the tx is displayed only once when filter is not used
image
4. the filtering by the token address doesn't work - [Wrapped Ether (WETH)](https://arbiscan.io/token/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1) address was used for filtering , but at the result you can see incoming NFT txs and incoming/outgoing txs with other tokens 
image

## Expected result
The filter by token address incoming txs should return only incoming txs with the token address from the filter

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #2499

## How this PR fixes it

The transaction modal now closes if the Safe changes.

## How to test it

1. Ensure the transaction modal is open.
2. Change Safe.
3. Observe the modal close.

The same should also happen with the a Safe of the _same_ address, but different chain.

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/tx-flow/index.tsx [hunk 1]
```diff
@@ -23,6 +24,7 @@ export const TxModalProvider = ({ children }: { children: ReactNode }): ReactEle
   const [fullWidth, setFullWidth] = useState<boolean>(false)
   const pathname = usePathname()
   const [, setLastPath] = useState<string>(pathname)
+  const { safe } = useSafeInfo()
```
Comment (katspaugh) [inline src/components/tx-flow/index.tsx:27]:
```suggestion
  const { safeAddress } = useSafeInfo()
```

**Review by katspaugh — APPROVED** [review]
