### PR TITLE
fix: Add padding to swap tx details

### LINKED ISSUE #4000: Uneven padding on TWAP order transaction details
## Bug description

The transaction details of TWAP orders have no left padding.

## Steps to reproduce
 1. Create a TWAP order and observe the transaction details of it ([example](https://safe-wallet-web.dev.5afe.dev/transactions/tx?safe=sep:0xF979f34D16d865f51e2eC7baDEde4f3735DaFb7d&id=multisig_0xF979f34D16d865f51e2eC7baDEde4f3735DaFb7d_0x7a22e4a07107440d56c8320f943da1611184a2688d8e5fce16d9f26fa9d08627)).

## Expected result

There is an equal padding around all transaction details.

## Obtained result

There is no left padding.

## Screenshots

image

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #4000

Fixes a regression introduced in #3893 

## How this PR fixes it

- Adds back the `swapOrder` class to the wrapper element

## How to test it

1. Open a Safe with a TWAP order in the history or queue
2. Observe there is padding in the tx details

## Screenshots
Screenshot 2024-07-29 at 15 38 22

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
Thanks Usame!

File: src/components/transactions/TxDetails/index.tsx [hunk 1]
```diff
@@ -76,7 +76,7 @@ const TxDetailsBlock = ({ txSummary, txDetails }: TxDetailsProps): ReactElement
       {/* /Details */}
       <div className={`${css.details} ${isUnsigned ? css.noSigners : ''}`}>
         {isOrderTxInfo(txDetails.txInfo) && (
-          <div>
+          <div className={css.swapOrder}>
```
Comment (katspaugh) [inline src/components/transactions/TxDetails/index.tsx:79]: The class exists in the CSS, right? Because that PR also removed it from there.

Comment (usame-algan) [reply src/components/transactions/TxDetails/index.tsx:79]: It only removed it for the border top property but the rest is still applied.

**Comment by katspaugh** [comment]
Tested, it's fixed now ✅
