### PR TITLE
fix: don't use `chainId` when calculating domain hash of <=1.2.0

### LINKED ISSUE #4613: Domain Hash Logic in Safe Versions `<= 1.2.0`
The fix for the domain and message hash in PR https://github.com/safe-global/safe-wallet-web/pull/4394 is incomplete. 

Safe versions `<= 1.2.0` use a legacy (i.e. without `chainId`) [`DOMAIN_SEPARATOR_TYPEHASH`](https://github.com/safe-global/safe-smart-account/blob/v1.0.0/contracts/GnosisSafe.sol#L20-L23) value:
```solidity
//keccak256(
//    "EIP712Domain(address verifyingContract)"
//);
bytes32 public constant DOMAIN_SEPARATOR_TYPEHASH = 0x035aff83d86937d35b32e04f0ddc6ff469290eef2f1b692d8a815c89404d4749;
```

I add this logic in my script here: https://github.com/pcaversaccio/safe-tx-hashes-util/pull/8. However, you can see that your domain hash is currently wrong. The issue is that in these lines you don't check for the Safe versions: https://github.com/safe-global/safe-wallet-web/blob/56e0bd08c5f2255b58266b13bd03ea08c1f00113/src/components/transactions/TxDetails/Summary/SafeTxHashDataRow/index.tsx#L20-L23

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #4613

## How this PR fixes it

For Safe versions <= 1.2.0, the domain separator typehash of the Safe contracts [does not include a `chainId`](https://github.com/safe-global/safe-smart-account/blob/v1.2.0/contracts/GnosisSafe.sol#L26):

```sol
bytes32 private constant DOMAIN_SEPARATOR_TYPEHASH = 0x035aff83d86937d35b32e04f0ddc6ff469290eef2f1b692d8a815c89404d4749;
```

For versions >= 1.3.0, [a `chainId` is included](https://github.com/safe-global/safe-smart-account/blob/v1.3.0/contracts/GnosisSafe.sol#L38):

```sol
bytes32 private constant DOMAIN_SEPARATOR_TYPEHASH = 0x47e79534a245952e8b16893a336b85a3d9ea9fa8c573f3d803afb92a79469218;
```

When calculating the domain hash, we do not take the contract version into account, calculating based on the newer domain separator typehash.

This conditionally includes the `chainId` when calculating the domain hash for the current Safe, therefore correcting it for <= 1.2.0 versions.

## How to test it

Using a Ledger device, observe the domain hash matching that in the interface for all versions from >= 1.0.0.

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/transactions/TxDetails/Summary/SafeTxHashDataRow/index.tsx [hunk 1]
```diff
@@ -4,6 +4,24 @@ import { type SafeTransactionData, type SafeVersion } from '@safe-global/safe-co
...
+  chainId,
+  safeAddress,
+  safeVersion,
+}: {
+  chainId: string
+  safeAddress: string
+  safeVersion: SafeVersion
+}): string {
+  return TypedDataEncoder.hashDomain({
+    ...(semverSatisfies(safeVersion, NEW_DOMAIN_TYPE_HASH_VERSION) && { chainId }),
```
Comment (katspaugh) [inline src/components/transactions/TxDetails/Summary/SafeTxHashDataRow/index.tsx:21]: ChatGPT has a point, it would be more readable with
`const includeChainId = semverSatisfies(safeVersion, NEW_DOMAIN_TYPE_HASH_VERSION)`

Comment (iamacook) [reply src/components/transactions/TxDetails/Summary/SafeTxHashDataRow/index.tsx]: Changed in 0fa8cff887e04e1998333e43c67bd3aa679f4aea.

**Review by katspaugh — APPROVED** [review]

**Comment by liliya-soroka** [comment]
Verified
