### PR TITLE
Fix: use wallet_addEthereumChain if cannot switch chain

### LINKED ISSUE #3515: MetaMask connection: unable to switch to the network, that isn't added in to current wallet
## Bug description
When user has selected network that isn't added to connected MetaMask wallet, clicking on "Switch to _Network name_" button  doesn't do anything.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Any

## Steps to reproduce
 1. Go to https://app.safe.global/welcome;
 2. Connect your MetaMask Wallet;
 3. In Network switcher dropdown select any Network, that isn't added to your Metamask;
 4. Click on your address in header;
 5. Click on "Switch to *Network name*".

## Expected result
MetaMask window appears, with request to "Allow this site to add a network?".

## Obtained result
Nothing happens on UI, MM throws next error in console:
`VM3088:1 MetaMask - RPC Error: Unrecognized chain ID "0xa4ec". Try adding the chain using wallet_addEthereumChain first. `
## Screenshots
image

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #3515

## How this PR fixes it

If `wallet_switchEthereumChain` throughs an "Unrecognized chain" error, we'll attempt to add that chain to the wallet.

### CODE REVIEW

File: src/services/tx/tx-sender/sdk.ts [hunk 1]
```diff
@@ -26,6 +26,37 @@ export const getAndValidateSafeSDK = (): Safe => {
...
+  const UNKNOWN_CHAIN_ERROR_CODE = 4902
+  const hexChainId = toQuantity(parseInt(chainId))
+
+  try {
+    return await walletProvider.request({
+      method: 'wallet_switchEthereumChain',
+      params: [{ chainId: hexChainId }],
+    })
+  } catch (error) {
+    if ((error as Error & { code: number }).code !== UNKNOWN_CHAIN_ERROR_CODE) {
```
Comment (usame-algan) [inline src/services/tx/tx-sender/sdk.ts:39]: Is it possible to use `asError` here?

File: src/services/tx/tx-sender/sdk.ts [hunk 2]
```diff
@@ -26,6 +26,37 @@ export const getAndValidateSafeSDK = (): Safe => {
...
+      throw error
+    }
+
+    const chain = await getChainConfig(chainId)
+
+    return await walletProvider.request({
```
Comment (usame-algan) [inline src/services/tx/tx-sender/sdk.ts:45]: I don't think `await` is needed here

File: src/services/tx/tx-sender/sdk.ts [hunk 3]
```diff
@@ -26,6 +26,37 @@ export const getAndValidateSafeSDK = (): Safe => {
   return safeSDK
 }
 
+async function switchOrAddChain(walletProvider: ConnectedWallet['provider'], chainId: string): Promise<void> {
+  const UNKNOWN_CHAIN_ERROR_CODE = 4902
```
Comment (usame-algan) [inline src/services/tx/tx-sender/sdk.ts:30]: I assume this is Metamask specific. Do we need to handle this with other wallets as well?

**Review by usame-algan — APPROVED** [review]

File: src/services/tx/tx-sender/sdk.ts (hunk 1 above)
Comment (katspaugh) [reply src/services/tx/tx-sender/sdk.ts:39]: Not much value here, we'd still have to cast it to have a code.

File: src/services/tx/tx-sender/sdk.ts (hunk 3 above)
Comment (usame-algan) [reply src/services/tx/tx-sender/sdk.ts:30]: I guess with MM we already cover a lot of cases and not sure how WC would behave if we try to call `wallet_addEthereumChain`.

**Comment by francovenica** [comment]
LGTM

Tested with Cello that was the network that gave me troubles on the first place
Deleted a few networks from the MM extension and add them again by switching to them
