### PR TITLE
fix: Add wrap on queue tx button container

### LINKED ISSUE #3386: Execute and replace button look broken in an ipad mini viewPort
## Bug description
Check the snapshot

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to a safe where tx are ready to be executed
 2. Change your browser to show an iPad mini viewport
 3. Check the execute and reject buttons

## Screenshots
image

### PR DESCRIPTION
**Pull request by daniel0ar**
## What it solves

Resolves #3386

## How this PR fixes it
It adds the flex-wrap property to the button container. I have also moved the styles of the Box container from inline properties to the corresponding css file for better maintenance.
 
## How to test it
Open http://localhost:3000/transactions/queue?safe=oeth%3A0x773D7c58941295aF412092efF5Aa3d188525e81a , open up the transation modal and check Execute and Replace buttons. 

## Screenshots
image

### CODE REVIEW

File: src/components/transactions/TxDetails/index.tsx [hunk 1]
```diff
@@ -109,7 +109,7 @@ const TxDetailsBlock = ({ txSummary, txDetails }: TxDetailsProps): ReactElement
           <TxSigners txDetails={txDetails} txSummary={txSummary} />
 
           {isQueue && (
-            <Box display="flex" alignItems="center" justifyContent="center" gap={1} mt={2}>
+            <Box className={`${css.buttons}`}>
```
Comment (usame-algan) [inline src/components/transactions/TxDetails/index.tsx:112]:
```suggestion
            <Box className={css.buttons}>
```

**Review by usame-algan — APPROVED** [review]
Just a small suggestion but looks good otherwise. Thanks!

File: src/components/transactions/TxDetails/index.tsx (hunk 1 above)
Comment (daniel0ar) [reply src/components/transactions/TxDetails/index.tsx]: Right! I have modified the unnecesary template strings found in the file.
