### PR TITLE
Fix: don't treat user rejections as errors

### LINKED ISSUE #2701: [Tx flow] Don't treat user rejection as an error
1) Don't log "user rejected" as an error to Sentry
Screenshot 2023-10-30 at 07 29 10
2) Don't show a notification for that
Screenshot 2023-10-30 at 07 30 42

### PR DESCRIPTION
**Pull request by jmealy**
## What it solves

Resolves #2701

## How this PR fixes it
When a user rejects a transaction through their connected wallet:
- do not log it as an error to sentry.
- do not send the user an error notification.
- Show `The transaction was rejected by the user.` in the tx execution box instead of a generic error message.

## How to test it
- Create a new transaction.
- When you are prompted to accept the transaction in Metamask, click reject.
- There should not be an error logged to sentry.
- There should be no error notification.
- The Execution box should say `The transaction was rejected by the user.`
- This will effect anywhere the user is prompted to accept or reject a transaction, including:
    - signing a tx
    - executing a tx
    - signing a message
    - batch txs
    - tx with spending limits
    - relayed txs
    - bulk txs
    - account recovery

## Screenshots
Before: 
Screenshot 2024-01-10 at 09 51 20

After:
Screenshot 2024-01-10 at 15 36 39

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/tx/SignOrExecuteForm/ExecuteForm.tsx [hunk 1]
```diff
@@ -170,6 +178,12 @@ export const ExecuteForm = ({
           </Box>
         )}
 
+        {isRejectedByUser && (
+          <Box mt={1}>
+            <ErrorMessage>The transaction was rejected by the user.</ErrorMessage>
```
Comment (katspaugh) [inline src/components/tx/SignOrExecuteForm/ExecuteForm.tsx:183]:
```suggestion
            <ErrorMessage>You've rejected the transaction.</ErrorMessage>
```
perhaps?

File: src/services/tx/tx-sender/dispatch.ts [hunk 2]
```diff
@@ -85,10 +86,12 @@ export const dispatchTxSigning = async (
   try {
     signedTx = await tryOffChainTxSigning(safeTx, safeVersion, sdk)
   } catch (error) {
-    txDispatch(TxEvent.SIGN_FAILED, {
-      txId,
-      error: asError(error),
-    })
+    if ((error as EthersError).code !== ErrorCode.ACTION_REJECTED) {
```
Comment (katspaugh) [inline src/services/tx/tx-sender/dispatch.ts:89]: This covers signatures but there's also executions and relays and other types of actions (basically all dispatch functions in this file).

File: src/components/tx/SignOrExecuteForm/ExecuteForm.tsx (hunk 1 above)
Comment (jmealy) [reply src/components/tx/SignOrExecuteForm/ExecuteForm.tsx:183]: Yeah make more sense 👍

File: src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx [hunk 3]
```diff
@@ -128,6 +136,8 @@ const ReviewSpendingLimitTx = ({
           <ErrorMessage error={submitError}>Error submitting the transaction. Please try again.</ErrorMessage>
         )}
 
+        {isRejectedByUser && <ErrorMessage>{`You've rejected the transaction.`}</ErrorMessage>}
```
Comment (usame-algan) [inline src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx:139]:
```suggestion
        {isRejectedByUser && <ErrorMessage>You&apos;ve rejected the transaction.</ErrorMessage>}
```

File: src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx [hunk 4]
```diff
@@ -96,9 +99,14 @@ const ReviewSpendingLimitTx = ({
...
-      setIsSubmittable(true)
-      setSubmitError(err)
+      if ('code' in err && err.code === ErrorCode.ACTION_REJECTED) {
+        setIsSubmittable(true)
+        setIsRejectedByUser(true)
+      } else {
+        logError(Errors._801, err)
+        setIsSubmittable(true)
+        setSubmitError(err)
+      }
```
Comment (usame-algan) [inline src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx:109]: We can reuse `isUserRejection` here and pull out `setIsSubmittable` from the condition since its set to true in both cases. This can also be done for the same block in `SignForm` and `ExecuteForm`.

File: src/components/tx/SignOrExecuteForm/ExecuteForm.tsx [hunk 5]
```diff
@@ -170,6 +178,12 @@ export const ExecuteForm = ({
           </Box>
         )}
 
+        {isRejectedByUser && (
+          <Box mt={1}>
+            <ErrorMessage>{`You've rejected the transaction.`}</ErrorMessage>
```
Comment (usame-algan) [inline src/components/tx/SignOrExecuteForm/ExecuteForm.tsx:183]:
```suggestion
            <ErrorMessage>You&apos;ve rejected the transaction.</ErrorMessage>
```

File: src/components/tx/SignOrExecuteForm/SignForm.tsx [hunk 6]
```diff
@@ -97,6 +105,12 @@ export const SignForm = ({
         )
       )}
 
+      {isRejectedByUser && (
+        <Box mt={1}>
+          <ErrorMessage>{`You've rejected the transaction.`}</ErrorMessage>
```
Comment (usame-algan) [inline src/components/tx/SignOrExecuteForm/SignForm.tsx:110]:
```suggestion
          <ErrorMessage>You&apos;ve rejected the transaction.</ErrorMessage>
```

File: src/hooks/messages/useSafeMessageNotifications.ts [hunk 7]
```diff
@@ -24,6 +25,10 @@ const SafeMessageNotifications: Partial<Record<SafeMsgEvent, string>> = {
   [SafeMsgEvent.SIGNATURE_PREPARED]: 'The message was successfully confirmed.',
 }
 
+const isUserRejection = (error: Error) => {
```
Comment (usame-algan) [inline src/hooks/messages/useSafeMessageNotifications.ts:28]: Maybe we can move this function into one of the utils files like `ethers-utils.ts` or create a new one for error utils so we don't have to define it twice and can reuse the logic in other places.

File: src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx (hunk 3 above)
Comment (usame-algan) [reply src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx:139]: This error message is defined in 4 places. I would suggest to extract it into a separate component like we do for some of the other errors like `NonOwnerError` to avoid duplication.

**Review by usame-algan — COMMENTED** [review]
Nice work on this! 💯 

Only got a few small refactoring suggestions.

File: src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx [hunk 8]
```diff
@@ -96,9 +99,14 @@ const ReviewSpendingLimitTx = ({
       setTxFlow(undefined)
     } catch (_err) {
       const err = asError(_err)
-      logError(Errors._801, err)
-      setIsSubmittable(true)
-      setSubmitError(err)
+      if ('code' in err && err.code === ErrorCode.ACTION_REJECTED) {
```
Comment (katspaugh) [inline src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx:102]: Might be good to create a utility for this, perhaps in `src/utils/wallets.ts`.

Actually, I've just checked and that file already has sWalletRejection :)

Comment (jmealy) [reply src/components/tx-flow/flows/TokenTransfer/ReviewSpendingLimitTx.tsx]: Perfect, thanks!

**Comment by katspaugh** [comment]
@jmealy we don't have a pre-commit hook for lint, because it takes such a long time, but please try to run `yarn lint --fix` locally before a commit.

**Review by katspaugh — APPROVED** [review]
👍

**Review by usame-algan — APPROVED** [review]
Thanks! 🚀

**Comment by liliya-soroka** [comment]
Opinion about the message: the user can mess up "reject tx as an owner in the connected walley" with reject original tx in the safe. "User rejected signing" was closer to the reality

**Comment by liliya-soroka** [comment]
1. Reject bulk execution : 
Current result: no notification, but the error on tx deatls is the same as "before"
image

**Comment by jmealy** [comment]
> User rejected signing

This makes sense, I'll change the message to `User rejected signing`

**Comment by liliya-soroka** [comment]
Verified
