### PR TITLE
fix: improve disable condition and tooltip tile on `TxSummary` buttons

### LINKED ISSUE #1932: Transaction error when trying to execute too fast
## Bug description

If the user tries to enter the transaction flow before that it fails because the Safe Core SDK has not been initialized yet.

We could disable transaction interactions until the Safe Core SDK instance is ready.

## Environment
 - Browser: any
 - Wallet: any
 - Chain: any

## Steps to reproduce
 1. Go to the Queue
 2. Reload the page
 3. Immediately try to Execute a queue transaction

## Expected result

There should be no error

## Obtained result

There is an error saying the safe core SDK has not been initialized

## Screenshots

Screenshot 2023-05-03 at 12 25 45

### PR DESCRIPTION
**Pull request by DiogoSoaress**
## What it solves

Resolves #1932

## How this PR fixes it
Includes the `coreSDK` initialization in the condition to disable the `<TxSummary>` buttons (`ExecuteTxButton`, `RejectTxButton` and `SignTxbutton`)
Improve tooltip description as per the disable condition

### Not next tx
1. Go to a Tx queue where a queued tx is fully signed but not the "Next" in the queue
2. Observe the execution icons is disabled and show a tooltip "Transaction {nonce} must be executed first"

### ~Transaction is pending execution~
~1. Go to a Tx queue and have 2 transactions ready to be executed
2. Execute the first one
3. Observe the execution icons in the second one is disabled and show a tooltip "Pending transaction must first succeed"~

### Safe SDK not initialized
1. Go to a Tx queue where there is a tx queued in the "next" nonce
2. Refresh the page
3. Try to hover the Execute/Reject/Sign buttons immediately
4. Observe they are disabled and show a tooltip 'Waiting for the SDK to initialize'

## Screenshots
Screenshot 2023-05-09 at 18 13 36

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [x] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/transactions/ExecuteTxButton/index.tsx [hunk 1]
```diff
@@ -26,9 +27,19 @@ const ExecuteTxButton = ({
   const txNonce = isMultisigExecutionInfo(txSummary.executionInfo) ? txSummary.executionInfo.nonce : undefined
   const isPending = useIsPending(txSummary.id)
   const { setSelectedTxId } = useContext(ReplaceTxHoverContext)
+  const safeSDK = getSafeSDK()
```
Comment (iamacook) [inline src/components/transactions/ExecuteTxButton/index.tsx:30]: `getSafeSDK` will not react to changes in `ExternalStore` state. We should use the hook when accessing the value.

File: src/components/transactions/ExecuteTxButton/index.tsx [hunk 2]
```diff
@@ -26,9 +27,19 @@ const ExecuteTxButton = ({
...
 
   const isNext = txNonce !== undefined && txNonce === safe.nonce
-  const isDisabled = !isNext || isPending
+  const isDisabled = !isNext || isPending || !safeSDK
+
+  const tooltipTitle =
+    isDisabled && !isNext
+      ? `Transaction ${safe.nonce} must be executed first`
```
Comment (iamacook) [inline src/components/transactions/ExecuteTxButton/index.tsx:37]: I don't think we need to show this, maybe even the button at all.

File: src/components/transactions/ExecuteTxButton/index.tsx [hunk 3]
```diff
@@ -26,9 +27,19 @@ const ExecuteTxButton = ({
...
+      : isPending
+      ? `There's a pending transaction`
```
Comment (iamacook) [inline src/components/transactions/ExecuteTxButton/index.tsx:39]: I would be more descriptive here, e.g.

```suggestion
      ? `You cannot execute while while a transaction is pending.`
```

File: src/components/transactions/ExecuteTxButton/index.tsx [hunk 4]
```diff
@@ -26,9 +27,19 @@ const ExecuteTxButton = ({
...
+      : !safeSDK
+      ? 'Waiting for the SDK to initialize'
```
Comment (iamacook) [inline src/components/transactions/ExecuteTxButton/index.tsx:41]: I'm not sure about this - it's somewhat technical for the "standard" user. It shouldn't happen to too long either.

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 3 above)
Comment (usame-algan) [inline src/components/transactions/ExecuteTxButton/index.tsx:39]: I like these new messages but would suggest to document them in the test plan of this PR. If possible, I would also suggest to extract this into a helper function that can be reused in all three buttons and write a few unit tests for it.

**Review by iamacook — COMMENTED** [review]
I've added some comments to the `ExecuteTxButton` but they stand for each. I'd suggest consulting with design about this.

A simpler solution would be disabling the submit button in the transaction `SignOrExecute` modal when the SDK is initialising.

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 3 above)
Comment (DiogoSoaress) [reply src/components/transactions/ExecuteTxButton/index.tsx:39]: I was trying to juggle between a more complete description and a more succinct one given it's a tooltip. Said that are you still in favor of the longer one?

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (DiogoSoaress) [reply src/components/transactions/ExecuteTxButton/index.tsx:30]: Nice catch! I was thinking of using the hook but for reason I used the getter and it worked so I've propagated it. It was a distraction

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 4 above)
Comment (DiogoSoaress) [reply src/components/transactions/ExecuteTxButton/index.tsx:41]: I've answered in https://github.com/safe-global/safe-wallet-web/pull/1969/files#r1189586069

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 3 above)
Comment (iamacook) [reply src/components/transactions/ExecuteTxButton/index.tsx:39]: Compared to the `title` on line 37, I think it needs more information. An alternative: "Pending transaction must first succeed".

**Comment by DiogoSoaress** [comment]
> A simpler solution would be disabling the submit button in the transaction SignOrExecute modal when the SDK is initialising.

That is already too late, the error appears when loading the values in that modal. That's why I think we should prevent opening it.

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (iamacook) [reply src/components/transactions/ExecuteTxButton/index.tsx:41]: I would drop the SDK altogether, e.g. "Initialising Safe".

**Comment by iamacook** [comment]
> That is already too late, the error appears when loading the values in that modal. That's why I think we should prevent opening it.

You could suppress the error until the SDK has initialised.

**Comment by DiogoSoaress** [comment]
> You could suppress the error until the SDK has initialised/failed to initialise.

The way we render `ErrorMessage` would delay any error until the SDK initialized/failed to initialize. But what I meant was that in order to display the tx data in the modal we rely on the SDK being initialized. See https://github.com/safe-global/safe-wallet-web/blob/3bc22a0425adf1e7c0ddc0a648b744051f95e48d/src/components/tx/modals/ConfirmTxModal/ConfirmProposedTx.tsx#L32-L46

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (DiogoSoaress) [reply src/components/transactions/ExecuteTxButton/index.tsx]: But that's not quite what's happening... do you have any suggestion other than "Loading" @usame-algan ?

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 3 above)
Comment (DiogoSoaress) [reply src/components/transactions/ExecuteTxButton/index.tsx]: Extracted the util and added the tests

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (iamacook) [reply src/components/transactions/ExecuteTxButton/index.tsx]: The SDK is an inherent part of the Safe though.

File: src/components/transactions/utils.ts [hunk 5]
```diff
@@ -0,0 +1,27 @@
+type DisabledPropsType =
+  | {
+      isNext: false
+      nonce: number
+      isPending: boolean
+      hasSafeSDK: boolean
+    }
+  | {
+      isNext?: boolean
+      nonce?: number
```
Comment (iamacook) [inline src/components/transactions/utils.ts:10]:
```suggestion
      isNext?: never
      nonce?: never
```

File: src/components/transactions/__tests__/utils.test.ts [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+      expect(getTxButtonTooltip(enabledTitle, disabledProps)).toBe('Transaction 2 must be executed first')
+    })
+
+    it('should return the "is tx pending" message', () => {
+      const enabledTitle = 'Execute'
+      const disabledProps = { ...disabledPropsBase, isPending: true }
+
+      expect(getTxButtonTooltip(enabledTitle, disabledProps)).toBe('Pending transaction must first succeed')
+      expect(true).toBe(true)
```
Comment (iamacook) [inline src/components/transactions/__tests__/utils.test.ts:27]:
```suggestion
```

File: src/components/transactions/ExecuteTxButton/index.tsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (usame-algan) [reply src/components/transactions/ExecuteTxButton/index.tsx]: Imo Loading is generic enough and still better than what we had before. We could also add no Tooltip in that case and just disable the button but I wouldn't mention any technical things there like the SDK.

**Comment by francovenica** [comment]
Issue:
The tx, while is being executed, shows the "Pending tx must succeed first", giving the impression that the button will be available at some point, but actually that button should never be since the tx will go away after being executed.
Or we don't show nothing at all in the tx that is being currently executed
Or we show a "Tx in execution"

image

**Comment by DiogoSoaress** [comment]
@usame-algan @francovenica What do you think of changing that tooltip to "Transaction in execution" ? dropping the "must execute first" that can be misleading.
Or, should we simply not show a tooltip when we have a pending tx?

**Comment by katspaugh** [comment]
Can we please wrap this up? The amount of discussion and attention this fix receives starts to worry me.

**Comment by francovenica** [comment]
I think not showing the tooltip in a executing tx is fine

**Comment by francovenica** [comment]
I still see tooltips while the tx is executing, maybe because the status is not "pending" but "processing" or "relaying".

Still I don't think is that big of a deal. I think we can leave it this way until we get feedback about it.
image
image

**Comment by DiogoSoaress** [comment]
> I still see tooltips while the tx is executing

These tooltips ("Execute", "Replace", "Confirm") were already in place and were not affected by this bug fix/improvement.

**Comment by francovenica** [comment]
Yes, I think we are done with this ticket. I'll pass it
