### PR TITLE
fix: Add hide address overflow on transaction history

### LINKED ISSUE #3197: Address overflows transaction details of transfers on mobile
## Bug description

Unlike other transaction details, asset transfer addresses overflow the transaction details container on mobile Chrome.

## Steps to reproduce
 1. Expand a transfer and observe the recipient address overflowing whereas those of other transaction types are cut off on mobile Chrome.

## Expected result

The recipient address in transaction 40 (see screenshot below) matches the style in transaction 39.

## Obtained result

The recipient address in transaction 40 overflows.

### PR DESCRIPTION
**Pull request by daniel0ar**
## What it solves

Resolves #3197

## How this PR fixes it
It truncates text with ellipsis on shrink, adding width 100% to TransferTxInfo container (Box) and hiding overflow on SrcEthHashInfo component (text Box itself).

## How to test it
Open http://localhost:3000/transactions/history?safe=oeth:0x773D7c58941295aF412092efF5Aa3d188525e81a , open accordion of any transaction and check if address shortens with "..." at the end on smaller viewports.

## Screenshots
image
image

### CODE REVIEW

File: src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx [hunk 1]
```diff
@@ -62,7 +62,7 @@ const SrcEthHashInfo = ({
   )
 
   return (
-    <div className={css.container}>
+    <div className={css.container} style={{ width: '100%' }}>
```
Comment (katspaugh) [inline src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx:65]: Could you move thos style it to styles.module.css to the `.container` class?

Comment (daniel0ar) [reply src/components/common/EthHashInfo/SrcEthHashInfo/index.tsx]: Done! Had not noticed it.

**Comment by daniel0ar** [comment]
This PR also solves issue #3313 , not sure how to add this to the PR description though.

**Comment by katspaugh** [comment]
Awesome, thank you!
