### PR TITLE
fix: safeTxGas for rejection txs

### LINKED ISSUE #3171: 1.1.1 Safes: Reject tx has safetxGas>0 and is not recognized as reject tx
## Bug description
1.1.1 Safes: Reject tx has safetxGas>0 and is not recognized as reject tx - https://github.com/5afe/safe-support/issues/379
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Create tx in the 1.1.1 safe
2. Reject tx via UI using "Reject tx" option
Current result: contract interaction tx is created with safetxgas>0, as result it's not recognised as reject tx created via UI

3. reject the tx again using "reject tx"
Current result: New reject tx is created with safetxgas=0, so it's recognised as reject tx

## Expected result
Make sure that reject tx has safetxgas=0 for the 1.1.1 safe

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves
The protocol-kit estimates the safeTxGas correctly but our SafeTxProvider overrides it with it's own estimation. Therefore this logic is removed with this commit so we only rely on the safeTxGas from the core-sdk.

Resolves #3171 

## How this PR fixes it
Remove all safeTxGas logic from our interface and let the protocol-kit handle it in `createTransaction` (except if the user explicitly overrides it)

## How to test it
- Use a 1.1.1 Safe and create a Rejection tx
- Observe that safeTxGas is 0 and it decodes correctly to a rejection

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by liliya-soroka** [comment]
I can confirm that reject tx has safetxgas=0 in the 1.1.1 
image

File: src/components/tx-flow/SafeTxProvider.tsx [hunk 1]
```diff
@@ -45,13 +45,12 @@ const SafeTxProvider = ({ children }: { children: ReactNode }): ReactElement =>
...
 
-  // Recommended nonce and safeTxGas
+  // Recommended nonce
   const recommendedNonce = useRecommendedNonce()
-  const recommendedSafeTxGas = useSafeTxGas(safeTx)
 
   // Priority to external nonce, then to the recommended one
   const finalNonce = isSigned ? safeTx?.data.nonce : nonce ?? recommendedNonce ?? safeTx?.data.nonce
-  const finalSafeTxGas = isSigned ? safeTx?.data.safeTxGas : safeTxGas ?? recommendedSafeTxGas ?? safeTx?.data.safeTxGas
+  const finalSafeTxGas = isSigned ? safeTx?.data.safeTxGas : safeTxGas ?? safeTx?.data.safeTxGas
```
Comment (compojoom) [inline src/components/tx-flow/SafeTxProvider.tsx:53]: Am I the only one who thinks that this is terrible to read?

Isn't:
```

let finalNonce;

if (isSigned) {
  finalNonce = safeTx?.data.nonce;
} else if (nonce) {
  finalNonce = nonce;
} else if (recommendedNonce) {
  finalNonce = recommendedNonce;
} else {
  finalNonce = safeTx?.data.nonce;
}
```

or 

```
let finalNonce;
if (isSigned) {
  finalNonce = safeTx?.data.nonce;
} else {
  finalNonce = nonce || recommendedNonce || safeTx?.data.nonce;
}
```

I know it is on multiple lines, but I can easily see what's going on. Where with ? : ?? ?? ?? I have to be lucky to see where it ends :D

Comment (katspaugh) [reply src/components/tx-flow/SafeTxProvider.tsx:53]: True, I think that ternary ran out of control :)

**Review by katspaugh — APPROVED** [review]
~Please merge since Liliya has confirmed it works.~

Actually we should also test regular txs in 1.1.1.

**Comment by francovenica** [comment]
Tested in a GNO safe 1.1.1

So Rejections in safes 1.1.1 look like "reject tx" and not "contract interactions" anymore, so that's fine

I had issues executing a change in policies in the safe: is this error related to this fix? 
I've seen this same error trying to execute a rejection in prod when trying to reproduce the reported issue (in this same safe)

This is the safe: the tx is fully signed so you can try to execute it yourself:
gno: 0x33018c7cbFa7C23ac461e7EF8b4451568aB909bE
image
image

**Comment by francovenica** [comment]
I tried that same tx in another GNO 1.1.1 safe and I didn't had the issue. Maybe is the safe?

What I did have issues was trying to change policies 1/2 to 2/2. I had to bumb up the gas limit manually for that tx
image

**Comment by francovenica** [comment]
Well, I tried those 2 tx giving me issues and now everything worked fine, so I'm puzzled what happened the first time.

I'll recheck during regression. You can merge this into the release
