### PR TITLE
fix: successfully connect after password recovery

### LINKED ISSUE #2863: Seedless: "Verify account with passcode" screen is not closed automatically after verification
## Bug description
Seedless: Full scree" Verify account with passcode" screen is not closed automatically after verification 
## Environment
 - Browser: Chrome
 - Wallet: MetaMask + Social login
 - Chain: any

## Steps to reproduce
 1. Connect MM to the web app
 2. click switch wallet and select social login
 3. login into the email with MFA ( the first time in the browser- clean local storage if required)
 Current result: Full screen " Verify account with passcode" is opened
 4. enter valid passcode and wait
 Current result: The screen is not closed automatically after verification, the user has to click X to close the screen

## Expected result
The screen should be closed automatically if the password validation was successful
## Screenshots
image

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves
The connect wallet request when connecting from the onboard module got stuck in a promise that never resolved after calling `connectWallet`.
Resolves #2863 

## How this PR fixes it
Does not allow two concurrent `connectWallet` requests.

## How to test it
- Ensure that for your social signer MFA is enabled
- Click connect wallet
- Select Social signer
- Login and recover password
- Observe the modal to close

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [x] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/hooks/wallets/useOnboard.ts [hunk 1]
```diff
@@ -110,9 +118,13 @@ export const connectWallet = async (
     wallets = await onboard.connectWallet(options)
   } catch (e) {
     logError(Errors._302, e)
+    isConnecting = false
+
     return
   }
 
+  isConnecting = false
```
Comment (katspaugh) [inline src/hooks/wallets/useOnboard.ts:126]: My bad, I deleted that.

**Review by katspaugh — APPROVED** [review]

**Comment by francovenica** [comment]
This ticket had to be merged in dev to test since social login doesn't work on PR's

It looks good.
Not using the onboardjs still works fine as well
