### PR TITLE
fix: Add social login feature toggle from config service

### LINKED ISSUE #2458: [Seedless-Onboarding]: Add feature toggle
## What is the feature about
We want to be able to enable this feature on a per chain basis.
Therefore we need to add a new feature toggle `MPC_SIGNER` which we will initially only enable on Gnosis Chain / Staging Görli.

Alternatively we could limit this feature by enabling / disabling the Social signer wallet type for the chain.

## Requirements
- [ ] Add feature toggle on staging
- [ ] Only offer social onboarding if feature toggle is on
- [ ] Make network selector read-only if connected via Social Login
- [ ] Show Login button disabled on other networks
- [ ] Skip to review screen on safe creation when social login is used

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #2458 

## How this PR fixes it

- Only shows social login in the onboard modal if its enabled in the config service
- The info message now displays all supported chains depending on the config service
- If the user is connected with a different wallet, the social login button will no longer show a connected state 

## How to test it

1. Open the welcome page on goerli staging CGW
2. Connect via Google
3. Connect to a different wallet either through the main button or the "Switch Wallet" button
4. Observe the Google button on the welcome page says "Continue with Google"
5. Switch to Polygon
6. Observe an info message saying that social login is only supported on Goerli
7. Open the Onboard modal
8. Observe no Social Login option

## Screenshots
Screenshot 2023-10-16 at 11 55 29
Screenshot 2023-10-16 at 11 56 45
Screenshot 2023-10-16 at 11 57 06

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/common/ConnectWallet/MPCLogin.tsx [hunk 1]
```diff
@@ -94,7 +117,13 @@ const MPCLogin = ({ onLogin }: { onLogin?: () => void }) => {
...
             }}
           />
-          Currently only supported on Gnosis Chain
+          Currently only supported on{' '}
+          {supportedChains.map((chain, idx) => (
+            <>
+              {chain}
+              {idx < supportedChains.length - 1 && ', '}
+            </>
+          ))}
```
Comment (schmanu) [inline src/components/common/ConnectWallet/MPCLogin.tsx:126]:
```suggestion
          {supportedChains.join(', ')}
```

File: src/components/common/ConnectWallet/MPCLogin.tsx [hunk 2]
```diff
@@ -8,18 +8,41 @@ import InfoIcon from '@/public/images/notifications/info.svg'
...
 
-const MPCLogin = ({ onLogin }: { onLogin?: () => void }) => {
+export const _getSupportedChains = (chains: ChainInfo[]) => {
+  return chains.reduce((result: string[], currentChain) => {
+    if (CGW_NAMES.SOCIAL_LOGIN && !currentChain.disabledWallets.includes(CGW_NAMES.SOCIAL_LOGIN)) {
+      result.push(currentChain.chainName)
+    }
+    return result
+  }, [])
+}
```
Comment (schmanu) [inline src/components/common/ConnectWallet/MPCLogin.tsx:24]: Nit: I feel like this is a bit simpler to read
```suggestion
 const filteredChains = chains.filter((chain) => CGW_NAMES.SOCIAL_LOGIN && !currentChain.disabledWallets.includes(CGW_NAMES.SOCIAL_LOGIN))
 return filteredChains.map((chainConfig) => chainConfig.chainName)
```

File: src/components/common/ConnectWallet/MPCLogin.tsx [hunk 3]
```diff
@@ -8,18 +8,41 @@ import InfoIcon from '@/public/images/notifications/info.svg'
...
+const useGetSupportedChains = () => {
+  const chains = useChains()
+
+  return _getSupportedChains(chains.configs)
```
Comment (schmanu) [inline src/components/common/ConnectWallet/MPCLogin.tsx:28]: Should we memoize this to reduce re-renders?

File: src/components/common/ConnectWallet/MPCLogin.tsx [hunk 4]
```diff
@@ -8,18 +8,41 @@ import InfoIcon from '@/public/images/notifications/info.svg'
...
+import useChains, { useCurrentChain } from '@/hooks/useChains'
+import { isSocialWalletEnabled } from '@/hooks/wallets/wallets'
+import { ONBOARD_MPC_MODULE_LABEL } from '@/services/mpc/module'
+import { CGW_NAMES } from '@/hooks/wallets/consts'
+import { type ChainInfo } from '@safe-global/safe-gateway-typescript-sdk'
 
-const MPCLogin = ({ onLogin }: { onLogin?: () => void }) => {
+export const _getSupportedChains = (chains: ChainInfo[]) => {
+  return chains.reduce((result: string[], currentChain) => {
+    if (CGW_NAMES.SOCIAL_LOGIN && !currentChain.disabledWallets.includes(CGW_NAMES.SOCIAL_LOGIN)) {
```
Comment (schmanu) [inline src/components/common/ConnectWallet/MPCLogin.tsx:19]: Do you know why we type the mapped type of `CGW_NAMES` as `string | undefined`?

Can it really be undefined? 
Should we refactor it as 
```ts
export const CGW_NAMES = {
  [WALLET_KEYS.INJECTED]: 'detectedwallet',
  [WALLET_KEYS.WALLETCONNECT_V2]: 'walletConnect_v2',
  [WALLET_KEYS.COINBASE]: 'coinbase',
  [WALLET_KEYS.PAIRING]: 'safeMobile',
  [WALLET_KEYS.SOCIAL]: 'socialLogin',
  [WALLET_KEYS.LEDGER]: 'ledger',
  [WALLET_KEYS.TREZOR]: 'trezor',
  [WALLET_KEYS.KEYSTONE]: 'keystone',
} as const
```

Or am I missing something about this mapping?

File: src/components/common/ConnectWallet/__tests__/MPCLogin.test.tsx [hunk 5]
```diff
@@ -96,7 +106,30 @@ describe('MPCLogin', () => {
...
-    expect(result.getByText('Currently only supported on Gnosis Chain')).toBeInTheDocument()
+    expect(result.getByText('Currently only supported on Goerli')).toBeInTheDocument()
     expect(await result.findByRole('button')).toBeDisabled()
   })
+
+  describe('getSupportedChains', () => {
+    it('returns chain names where social login is enabled', () => {
+      const mockEthereumChain = { chainId: '1', chainName: 'Ethereum', disabledWallets: ['socialLogin'] } as ChainInfo
+      const mockGnosisChain = { chainId: '100', chainName: 'Gnosis Chain', disabledWallets: ['Coinbase'] } as ChainInfo
+      const mockGoerliChain = { chainId: '5', chainName: 'Goerli', disabledWallets: ['TallyHo'] } as ChainInfo
```
Comment (schmanu) [inline src/components/common/ConnectWallet/__tests__/MPCLogin.test.tsx:117]: Nit: If we leave it empty we test that it also works if no wallets are disabled.

```suggestion
      const mockGoerliChain = { chainId: '5', chainName: 'Goerli', disabledWallets: [] } as ChainInfo
```

File: src/components/common/ConnectWallet/MPCLogin.tsx (hunk 4 above)
Comment (usame-algan) [reply src/components/common/ConnectWallet/MPCLogin.tsx:19]: I was also wondering about that. The only reason I can see is that the `WALLET_MODULES` and `CGW_NAMES` should be coupled but currently are not so it could happen that we try to access a key in `CGW_NAMES` that doesn't exist.

**Review by schmanu — APPROVED** [review]
