### PR TITLE
fix: inconsistent layout in dashboard pending transactions view 

### LINKED ISSUE #3762: Misalignment of pending transactions on dashboard
## Bug description

If the name of the recipient/action is too wide in the list of pending transactions, the threshold indicator and arrow move to a newline that is not right aligned.

## Steps to reproduce
 1. Queue a transaction with a long-named recipient and observe the misaligned indicator.

## Expected result

Threshold indicator is aligned to the right.

## Obtained result

Threshold is aligned to the left.

## Screenshots

image

### PR DESCRIPTION
**Pull request by Shaik-Sirajuddin**
## What it solves
Resolves #3762
This PR introduces a UI fix where recent transactions layout on dashboard is rendered in multiple rows , when contract names have long text.

## How this PR fixes it
Transaction info is restricted to single row on desktop , with two rows as default on mobile devices.

## How to test it
1) visit app.safe.global 
2) Login into a safe account requiring multisig
3) Broadcast a transaction to a contract function with long name 
4) Visit Dashboard 
5) The individual transaction is shown in multiple rows
6) Alternative edit the function name via inspect to increase text length

## Screenshots
Before : 
Desktop :
Screenshot from 2024-08-03 22-40-52
Mobile :
Screenshot from 2024-08-03 22-40-40

After : 
Desktop : 
Screenshot from 2024-08-03 21-58-26
Mobile : 
Screenshot from 2024-08-03 21-58-11

## Checklist
* [x] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by Shaik-Sirajuddin** [comment]
> I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

**Comment by Shaik-Sirajuddin** [comment]
recheck

File: src/components/transactions/TxInfo/index.tsx [hunk 1]
```diff
@@ -84,56 +87,67 @@ export const TransferTx = ({
...
   }
 
   if (isCreationTxInfo(info)) {
-    return <CreationTx info={info} />
+    return <CreationTx info={info} truncateText={truncateText} />
   }
 
   if (isOrderTxInfo(info)) {
-    return <SwapTx info={info} />
+    return <SwapTx info={info} truncateText={truncateText} />
```
Comment (katspaugh) [inline src/components/transactions/TxInfo/index.tsx:150]: Can we avoid parametrizing all these components? Are there cases where we _don't_ want to truncate the text?

Comment (Shaik-Sirajuddin) [reply src/components/transactions/TxInfo/index.tsx]: Found that Apart from Pending Transaction section in home page <TxInfo> component is also being used in Transactions Page , BatchTxList component

Transactions page takes 80% width of screen , it would have enough space in most cases
As suggested 
Applied truncateText as default to handle very large function names

**Comment by Shaik-Sirajuddin** [comment]
recheck

**Review by katspaugh — APPROVED** [review]
Looks good now, thanks much!

**Comment by katspaugh** [comment]
@francovenica will you be able to test this branch locally or should I merge it to dev and you test on there?

**Comment by francovenica** [comment]
@katspaugh Merge it into dev
