### PR TITLE
fix: show input error if chosen nonce is not an integer

### LINKED ISSUE #3159: Nonce input allows decimal numbers
## Bug description
The input shouldn't even allow you to put decimal numbers.

Note: There is still a validation when you try to execute the tx, so is not a major issue.

Note 2: This ticket should be tackled after ticket https://github.com/safe-global/safe-wallet-web/pull/3127 is merged in dev since that ticket changes the behaviour of the nonce input

## Environment
 - Browser: any
 - Wallet: Any
 - Chain: Any
 - Env: Prod 1.27

## Steps to reproduce
 1. Go to a safe you own
 2. Start any tx (owner adding, send funds...)
 3. Input in the nonce field a decimal number 

## Expected result
Decimal numbers shouldn not be allowed in the input

## Screenshots
image

### PR DESCRIPTION
**Pull request by jmealy**
## What it solves

Resolves #3159 

## How this PR fixes it
Show an error when user inputs a non integer number

## How to test it
- On the execute transaction screen, try to change the nonce to a number with a decimal point.
- It should show an error.
- Changing to an integer should work as before.

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/tx-flow/common/TxNonce/index.tsx [hunk 1]
```diff
@@ -101,6 +101,7 @@ enum ErrorMessages {
   NONCE_TOO_HIGH = 'Nonce is too high',
   NONCE_TOO_FAR = 'Nonce is much higher than the current nonce',
   NONCE_GT_RECOMMENDED = 'Nonce is higher than the recommended nonce',
+  NONCE_MUST_BE_INTEGER = 'Nonce must be an integer',
```
Comment (usame-algan) [inline src/components/tx-flow/common/TxNonce/index.tsx:104]: I wonder if non-technical users know what an integer is. Maybe we could say `Nonce must be a whole number` or `Nonce can't contain decimals`

**Review by usame-algan — APPROVED** [review]
Looks good 👍

**Comment by francovenica** [comment]
LGTM

Checked that you see the error and the input resets if you put a decimal numbers (it trims it out if you click outside the input)

image
