### PR TITLE
fix: edit styles for assets in Overview widget

### LINKED ISSUE #3068: Dashboard overview widget UI fixes
## Bug description
Not a bug, but an update to the overview dashboard widget that shows balance.  

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the Dashboard page of any Safe account.

## Expected result
- Change the text style of the amount of assets stored (better readability);
- Buttons should fill the container's width.  

[Design reference in Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=9249%3A65172&mode=design&t=omKO5xezFboyvYR6-1)

## Screenshots
Screenshot 2024-01-04 at 17 57 27

### PR DESCRIPTION
**Pull request by 000000armor**
## What it solves

Resolves #3068

## How this PR fixes it
Added styles
## How to test it
Check styles

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

## Additional comment
It is my first PR for your repository. Please let me know if I have made any mistakes related to your coding style guidelines

### CODE REVIEW

File: src/components/dashboard/Overview/Overview.tsx [hunk 1]
```diff
@@ -180,12 +200,16 @@ const Overview = (): ReactElement => {
...
-
-                <Grid item xs={6} sm="auto">
+              <Grid
+                container
+                mt={3}
+                spacing={1}
+                flexWrap="wrap"
+                style={{ display: 'flex', justifyContent: 'space-between' }}
+              >
+                <BuyCryproButton />
```
Comment (katspaugh) [inline src/components/dashboard/Overview/Overview.tsx:210]: I would move `<Grid item style={{ flex: 1 }}>` here, instead of inside the `BuyCryproButton`.

**Comment by katspaugh** [comment]
Could you post a couple before and after screenshots? Thank you!

File: src/components/dashboard/Overview/Overview.tsx (hunk 1 above)
Comment (000000armor) [reply src/components/dashboard/Overview/Overview.tsx:210]: Unfortunately, it is not possible, because we control show/hide logic inside of the button, when we put `<Grid />` wrapper outside the button it will hold the space and move other buttons in Overview widget

Comment (katspaugh) [reply src/components/dashboard/Overview/Overview.tsx:210]: Ah, true, thanks!

**Comment by katspaugh** [comment]
And also accept the CLA pls :)

**Comment by 000000armor** [comment]
---
I have read the CLA Document and I hereby sign the CLA
---

**Comment by 000000armor** [comment]
recheck

**Comment by 000000armor** [comment]
> And also accept the CLA pls :)

done

**Comment by 000000armor** [comment]
CleanShot 2024-02-02 at 00 04 55
CleanShot 2024-02-02 at 00 04 20
@katspaugh 
There are two cases: one with the 'Buy Crypto' button and one without it. Sorry for the late reply

**Comment by katspaugh** [comment]
The CLA signature didn't work, could you paste it verbatim, without the horizontal lines?

**Comment by 000000armor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 000000armor** [comment]
@katspaugh done, please trigger rerun of the pipeline

**Comment by katspaugh** [comment]
It worked, thank you!
