### PR TITLE
fix: trim/remove leading zeros from values

### LINKED ISSUE #2281: Spending limits - Error show when blank spaces are in the amount input
## Bug description
When creating a spending limit, if there are blank spaces in front of the number an error "Amount too small" is shown. In other amount inputs (like send funds) blank characters are ignored, the same should happen for spending limit creation

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Any
 - Env: Current prod v1.14 and new RC v1.15

## Steps to reproduce
 1. Go to the Spending limit and start the creation of one
 2. Pick any token and enter any amount
 3. Add after the amount at least 1 blank space

## Expected result
No errors should pop up

## Obtained result
An error saying amount too small

## Screenshots
image

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #2281

## How this PR fixes it

The value of the `NumberField` component now trims and removes leading zeros.

## How to test it

The aforementioned component is used in:

- Token amount field
- `safeTxGas` field
- Transaction filter: amount, nonce fields
- Advanced params: wallet nonce, max prio fee, max fee/gas price fields
- Approval editor: value field
- Transaction nonce field

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/common/TokenAmountInput/index.tsx [hunk 1]
```diff
@@ -67,6 +67,10 @@ const TokenAmountInput = ({
           {...register(TokenAmountFields.amount, {
             required: true,
             validate: validate ?? validateAmount,
+            onChange: (event) => {
+              event.target.value = event.target.value.trim()
+              return event
+            },
```
Comment (usame-algan) [inline src/components/common/TokenAmountInput/index.tsx:73]: As an additional thing, should we also remove leading zeroes?

**Review by usame-algan — APPROVED** [review]

File: src/components/common/TokenAmountInput/index.tsx (hunk 1 above)
Comment (iamacook) [reply src/components/common/TokenAmountInput/index.tsx]: Great idea! I've added the logic to the `NumberField` directly.

**Comment by francovenica** [comment]
LGTM
