### PR TITLE
fix: Track number of delegate transactions

### LINKED ISSUE #4206: Add analytics for delegate support
## What is the feature about

In #1825 we added delegate support in the UI. It would be good to know how much this is being used.

## The list of requirements

- Track an event when a delegate proposes a transaction

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #4206

## How this PR fixes it

- Extends `trackTxEvents` to handle delegate form submissions

## How to test it

1. Open a Safe that has a delegate
2. Create a transaction as a delegate
3. Observe a GA event being emitted once the user submits the tx in their wallet

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/tx/SignOrExecuteForm/index.tsx [hunk 1]
```diff
@@ -63,8 +63,13 @@ const trackTxEvents = (
...
   isExecuted: boolean,
   isRoleExecution: boolean,
+  isDelegateCreation: boolean,
 ) => {
-  const creationEvent = isRoleExecution ? TX_EVENTS.CREATE_VIA_ROLE : TX_EVENTS.CREATE
+  const creationEvent = isRoleExecution
+    ? TX_EVENTS.CREATE_VIA_ROLE
+    : isDelegateCreation
+    ? TX_EVENTS.CREATE_VIA_DELEGATE
+    : TX_EVENTS.CREATE
```
Comment (compojoom) [inline src/components/tx/SignOrExecuteForm/index.tsx:72]: you know that nested nested ternaries trigger give me such anxiety :)

**Review by compojoom — APPROVED** [review]

File: src/components/tx/SignOrExecuteForm/index.tsx (hunk 1 above)
Comment (usame-algan) [reply src/components/tx/SignOrExecuteForm/index.tsx:72]: Lets hope this is the last flag we have to pass to this function 🤞

**Comment by liliya-soroka** [comment]
Verified
